language: java
env:
  #- GRADLE_VERSION=2.14 JAVA_VERSION=openjdk8
  # java 9 and gradle 2 not supported
  #- GRADLE_VERSION=3.5.1 JAVA_VERSION=openjdk8
  # java 9 and gradle 3 not supported
  - GRADLE_VERSION=4.0.1 JAVA_VERSION=openjdk8
  # Java 9 doesn't work with Gradle 4.0
  #- GRADLE_VERSION=4.0.1 JAVA_VERSION=oraclejdk9
  - GRADLE_VERSION=4.10.3 JAVA_VERSION=openjdk8
  - GRADLE_VERSION=4.10.3 JAVA_VERSION=oraclejdk9
  - GRADLE_VERSION=5.3.1 JAVA_VERSION=openjdk8
  - GRADLE_VERSION=5.3.1 JAVA_VERSION=oraclejdk9
before_cache:
# Per https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - node_modules
  # Per https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - .gradle
before_install:
  # sdkman helps to install different gradle versions
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
script:
  - sdk install gradle $GRADLE_VERSION
  - jdk_switcher use $JAVA_VERSION
  - gradle check
