version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/gradleinclude"
    update_schedule: "daily"
